// Game constants and mutable settings
// Player stats
const PLAYER_MAX_HEALTH = 100;
const PLAYER_SPEED = 4;
const PLAYER_JUMP_STRENGTH = -20;
const PLAYER_PUNCH_DAMAGE = 15;
const PLAYER_PUNCH_DURATION_MS = 150;
const PLAYER_COLOR = '#00ff41';

// Enemy defaults (mutable per difficulty)
let ENEMY_HEALTH = 50;
let ENEMY_SPEED = 2;
let ENEMY_PUNCH_DAMAGE = 10;
const ENEMY_PUNCH_DURATION_MS = 300;
const ENEMY_COLOR = '#ff073a';

// Boss defaults
let BOSS_HEALTH = 300;
let BOSS_SPEED = 1.5;
let BOSS_PUNCH_DAMAGE = 25;
const BOSS_PUNCH_DURATION_MS = 500;
const BOSS_COLOR = '#bf00ff';

// Game rules
const GRAVITY = 0.5;
const MAX_ENEMIES = 3;
const KILLS_TO_SPAWN_BOSS = 5;

// AI settings
const AI_CHASE_DISTANCE = 160;
const AI_RETREAT_DISTANCE = 100;
const AI_ATTACK_RANGE_BOSS = 180;
const AI_ATTACK_RANGE_NORMAL = 120;

// Export as globals for simple script usage (no module system)
window.GC = {
  // constants
  PLAYER_MAX_HEALTH, PLAYER_SPEED, PLAYER_JUMP_STRENGTH, PLAYER_PUNCH_DAMAGE, PLAYER_PUNCH_DURATION_MS, PLAYER_COLOR,
  ENEMY_HEALTH, ENEMY_SPEED, ENEMY_PUNCH_DAMAGE, ENEMY_PUNCH_DURATION_MS, ENEMY_COLOR,
  BOSS_HEALTH, BOSS_SPEED, BOSS_PUNCH_DAMAGE, BOSS_PUNCH_DURATION_MS, BOSS_COLOR,
  GRAVITY, MAX_ENEMIES, KILLS_TO_SPAWN_BOSS,
  AI_CHASE_DISTANCE, AI_RETREAT_DISTANCE, AI_ATTACK_RANGE_BOSS, AI_ATTACK_RANGE_NORMAL
};
